# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23aa581bdee6921347fb93128b5dd099d88e227ee397ca2decbeeb6eec5bb638832a856fd0ba381446c10e043b6151a1ebb13ca580f5541b475b108b9495f9ad

test:
  secret_key_base: 511c6837ce73febb5c9e3244988fc082e39ebec81980575d8aea8aa4abda613295dee54270e255b78de66691cd882ac2a2887b70a4db36b025f529082898f227

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
